apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-world
  name: hello-world
  namespace: udacity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - image: etapau/hello-world:udacity
          imagePullPolicy: Always
          name: hello-world
          ports:
            - containerPort: 9000
              protocol: TCP
          livenessProbe:
            httpGet:
              port: 9000
              path: /healthz  #This path was /nginx_status which was invalid and returned a 500 error.  updated to /healthz to get the response expected for the project.
            initialDelaySeconds: 2
            periodSeconds: 2
      nodeSelector:
        kubernetes.io/os: linux
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world
  namespace: udacity
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 9000
  selector:
    app: hello-world
  type: LoadBalancer